// Shared team data for all team pages
export const teamsData: Record<string, {
  logo: string;
  region: string;
  strRank: number | string;
  worldRank: number | string;
  players: { name: string; flag: string; months: number; maps: number; rating: number; status: string }[];
  coach: string;
  weeksInTop30: number;
  avgAge: number;
}> = {
  'HOLOXY': {
    logo: '/teams/holoxy.png',
    region: 'Russia',
    strRank: 1,
    worldRank: 1,
    players: [
      { name: 'Aler1t514', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'N1rMys', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'L1mpiks', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'BoryaKomfort', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'd9dyaDima', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: '-',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
  'Impact Team': {
    logo: '/teams/impact.png',
    region: 'Russia',
    strRank: 2,
    worldRank: 2,
    players: [
      { name: 'Qwerty', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Ka1yser', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'yborshiiik', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Kurnach', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'makent0w', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: '-',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
  'MGL': {
    logo: '/teams/mgl.png',
    region: 'Russia',
    strRank: 3,
    worldRank: 3,
    players: [
      { name: 'Varadka', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'masuka_ment', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: '-k0bayashii', flag: '🇰🇿', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'speNder', flag: '🇰🇿', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'dark', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: '-',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
  'DEAD EYES': {
    logo: '/teams/deadeyes.png',
    region: 'Russia',
    strRank: 4,
    worldRank: 4,
    players: [
      { name: 'solac3', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'y9ko', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Famlikus', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'x0nes', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Troyka', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: '-',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
  'PLATINA': {
    logo: '/teams/platina.png',
    region: 'Russia',
    strRank: 5,
    worldRank: 5,
    players: [
      { name: 'fly143', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'puywx', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: '12fth', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'low11ness', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'qfls-', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: '-',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
  'HAWKS': {
    logo: '/teams/hawks.png',
    region: 'Russia',
    strRank: 10,
    worldRank: 12,
    players: [
      { name: 'I1uvatar', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'hamp1kx', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Pruwka', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'ex3empl66', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'killoYa1337', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: '-',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
  'BEBRIKI': {
    logo: '/teams/bebriki.png',
    region: 'Russia',
    strRank: 12,
    worldRank: 8,
    players: [
      { name: 'Sinfulll', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'kurotosocial', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'snapi', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'QweFerz', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'z1lJekxxx666', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: '-',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
  'XENOX ACADEMY': {
    logo: '/teams/xenoxac.png',
    region: 'Russia',
    strRank: '-',
    worldRank: '-',
    players: [
      { name: 'SkyCrole', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'oTMoRoZzOK1337', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Sale', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'sojerio', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'BOBNOCТЬ', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: '-',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
  'HOXY NXT': {
    logo: '/teams/hoxynxt.png',
    region: 'Europe',
    strRank: 6,
    worldRank: 6,
    players: [
      { name: 'de0', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'OWNAGE', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: '???', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: '???', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: '???', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: 'unloveb0y',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
  'Imperium eSports': {
    logo: '/teams/imperium.png',
    region: 'Russia',
    strRank: 7,
    worldRank: 7,
    players: [
      { name: 'exce1lent', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Kub1kus', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Hanzoku', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'NAYMES', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Tik1njo', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: '-',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
  'KeHeXiLi IG': {
    logo: '/teams/kehexili.png',
    region: 'Russia',
    strRank: 8,
    worldRank: 9,
    players: [
      { name: 'sunketsu', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'x1nax', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'L1nia', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'keran1s', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'sabrox', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: '-',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
  'Valhalla': {
    logo: '/teams/valhalla.png',
    region: 'Russia',
    strRank: 9,
    worldRank: 10,
    players: [
      { name: 'Shuki', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Dexi1Z', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Axell', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Fisco', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Nics', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: '-',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
  'GODBLESS TEAM': {
    logo: '/teams/godbless.png',
    region: 'Russia',
    strRank: 11,
    worldRank: 11,
    players: [
      { name: 'bff3zz', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'quakaaaa', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'm1sst', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'maLLii', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'znx', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: '-',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
  'KLEPTO TEAM': {
    logo: '/teams/klepto.png',
    region: 'Russia',
    strRank: 13,
    worldRank: 13,
    players: [
      { name: 'Gen by', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Kumarik', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Cement bakin', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Sopog', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: '.', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: '-',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
  'PRIMUS': {
    logo: '/teams/primus.png',
    region: 'Europe',
    strRank: 14,
    worldRank: 14,
    players: [
      { name: 'novaprospekt', flag: '🇰🇿', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'ggg', flag: '🇰🇿', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'hokvv', flag: '🇺🇦', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'swok1nz', flag: '🇹🇷', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'Hoopz', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: '-',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
  'AuraTeam': {
    logo: '/teams/aurateam.png',
    region: 'Russia',
    strRank: '-',
    worldRank: '-',
    players: [
      { name: 'vilchinskii', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'raze', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'rev2rse', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'm1s', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
      { name: 'd0tto', flag: '🇷🇺', months: 0, maps: 0, rating: 0, status: 'STARTER' },
    ],
    coach: '-',
    weeksInTop30: 0,
    avgAge: 18.1,
  },
};

export const eventsData = [
  { name: 'MDK Season 4', logo: '/events/mdkseason4.png', date: 'Mar 9-10', path: '/events/mdk-s4', banner: '/banner-bg.jpg' },
  { name: 'FROGSTAR | CS:GO TOUR...', logo: '/events/frogstar.png', date: 'Mar 20-22', path: '/events/frogstar', banner: '/banner-fs.jpg', fullName: 'FROGSTAR | CS:GO TOURNAMENT #1' },
];
